# Generated by Django 4.1.4 on 2023-03-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('apporder', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='finalimages')),
                ('url', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('pinned', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
