# Generated by Django 4.1.4 on 2023-03-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('var', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apps',
            name='color',
        ),
    ]
