# Generated by Django 4.1.4 on 2023-03-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_systemvar_remove_apps_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
