# Generated by Django 4.1.4 on 2023-04-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_apps_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppOrder',
        ),
        migrations.AlterField(
            model_name='apps',
            name='icon',
            field=models.ImageField(upload_to='appicon'),
        ),
    ]
